# Contains fuzzy mappings to identify similar keywords or names

keywords = {
  "genetic algorithm": "evolutionary computing",
  "network intrusion detection": "intrusion detection",
  "mobile agents": "distributed systems",
  "mutual information": "information theory",
  "bayesian network based detection": "bayesian networks",
  "evolutionary computing": "computational intelligence",
  "economics of it security": "information security",
  "manet": "ad hoc networks",
  "cic-ids2017": "datasets",
  "one-class svm": "support vector machine",
  "support vector machine": "machine learning",
  "application-layer protocols": "network protocols",
  "intrusion detection system": "intrusion detection systems",
  "ahp-topsis": "decision-making",
  "insider attack": "cybersecurity",
  "krill herd optimization algorithm": "optimization",
  "fuzzy": "fuzzy logic",
  "internet of things": "iot",
  "false alarm ratio": "intrusion detection metrics",
  "data mining": "machine learning",
  "cisco packet tracer": "network simulation tools",
  "network ids": "intrusion detection systems",
  "artificial neural networks": "neural networks",
  "network security": "cybersecurity",
  "security": "cybersecurity",
  "neural network": "machine learning",
  "passive protocol analysis": "network protocols",
  "deep learning": "neural networks",
  "network intrusion detection systems (nids)": "intrusion detection systems",
  "optimization": "computational intelligence",
  "particle swarm optimization": "optimization",
  "anomaly detection": "intrusion detection",
  "classification and regression trees": "decision trees",
  "system call": "operating systems",
  "acquaintance management": "collaboration",
  "information security": "cybersecurity",
  "principal component analysis": "dimensionality reduction",
  "pairwise learning": "machine learning",
  "classifier machine learning": "machine learning",
  "sampling": "data preprocessing",
  "decision tree": "decision trees",
  "least square support vector machine": "support vector machine",
  "misuse detection": "intrusion detection",
  "soft computing": "computational intelligence",
  "computer security": "cybersecurity",
  "ids analysis": "intrusion detection systems",
  "attack taxonomy": "cybersecurity",
  "intrusion detection systems (idss)": "intrusion detection systems",
  "sensor fusion": "data fusion",
  "missed alarms": "intrusion detection metrics",
  "lstm": "neural networks",
  "pattern recognition": "machine learning",
  "genetic fuzzy systems": "fuzzy logic",
  "association rules": "data mining",
  "machine learning": "computational intelligence",
  "advanced metering infrastructure": "iot",
  "machine-learning": "machine learning",
  "cuttlefish algorithm": "optimization",
  "intrusive anomalies": "anomaly detection",
  "tcpdump": "network monitoring tools",
  "analytical modeling": "modeling",
  "host-based intrusion detection systems": "intrusion detection systems",
  "minimum cross entropy": "optimization",
  "cybersecurity": "information security",
  "stacknet": "ensemble learning",
  "hyperparameters": "machine learning",
  "honeypot": "network security",
  "attack": "cybersecurity",
  "evasion attacks": "cybersecurity",
  "random forests": "ensemble learning",
  "naive bayesian classifier": "bayesian networks",
  "artificial attack": "cybersecurity",
  "denial of service": "cybersecurity",
  "feature selection": "data preprocessing",
  "ensemble learning classifier": "ensemble learning",
  "wireless sensor network": "iot",
  "smart grid": "iot",
  "challenge-based trust mechanism": "trust management",
  "wsn": "wireless sensor network",
  "streaming service": "iot",
  "collaborative networks": "collaboration",
  "industry 4.0": "iot",
  "kdd 99 dataset": "datasets",
  "ad hoc networks": "distributed systems",
  "sendmail": "email protocols",
  "iot": "internet of things",
  "feature reduction": "dimensionality reduction",
  "markov blanket": "bayesian networks",
  "security configuration": "cybersecurity",
  "bidirectional long short-term memory": "neural networks",
  "chebyshev inequality": "statistics",
  "roc curves": "classification metrics",
  "neuro-fuzzy": "fuzzy logic",
  "software configuration": "software engineering",
  "insertion attacks": "cybersecurity",
  "ids": "intrusion detection systems",
  "decision jungle": "ensemble learning",
  "visualization": "data analysis",
  "machine learning approaches": "machine learning",
  "false alarms": "intrusion detection metrics",
  "hidden markov model": "probabilistic models",
  "estimation of distribution algorithm": "optimization",
  "cyber security": "cybersecurity",
  "smart environments": "iot",
  "layer wise relevance propagation": "explainable ai",
  "classification": "machine learning",
  "computer misuse": "cybersecurity",
  "ids coverage": "intrusion detection systems",
  "dynamic protocol analysis": "network protocols",
  "trust management": "collaboration",
  "security policies": "cybersecurity",
  "id3 algorithm": "decision trees",
  "inductive learning": "machine learning",
  "deep neural networks": "neural networks",
  "ids evaluation": "intrusion detection systems",
  "explainable artificial intelligence": "explainable ai",
  "cost-sensitive modeling": "modeling",
  "collaborative ids": "intrusion detection systems",
  "weka": "data mining tools",
  "distributed approaches": "distributed systems",
  "c4.5": "decision trees",
  "bayesian networks": "probabilistic models",
  "libsvm": "support vector machine",
  "explainable ai": "explainable artificial intelligence",
  "blockchain technology": "blockchain",
  "multi-robot systems": "distributed systems",
  "mobile ad hoc network": "ad hoc networks",
  "random forest": "ensemble learning",
  "consensus algorithm": "blockchain",
  "ensemble design": "ensemble learning",
  "event correlation": "data analysis",
  "data-dependent decision fusion": "data fusion",
  "ensemble-based methods": "ensemble learning",
  "wireless networks": "networking",
  "collaboration": "collaborative networks",
  "execution tracing": "software engineering",
  "kdd cup 99": "datasets",
  "frequent episodes": "data mining",
  "intrusion signatures": "intrusion detection",
  "hybrid ids": "intrusion detection systems",
  "one-vs-one": "machine learning",
  "hybrid intelligent system": "artificial intelligence",
  "pso": "particle swarm optimization",
  "intrusion detection": "intrusion detection systems",
  "coronavirus pandemic": "global events",
  "firewalls": "network security",
  "anomaly-based ids": "intrusion detection systems",
  "pca": "dimensionality reduction",
  "shell command": "operating systems",
  "profiling": "data analysis",
  "multilayer perceptron": "neural networks",
  "linear correlation coefficient": "statistics"
}

methodologies = {
  "gridsearchcv": "hyperparameter optimization",
  "pairwise learning": "machine learning",
  "voting classifier": "ensemble learning",
  "bidirectional long short-term memory": "neural networks",
  "multi-expression programming": "computational intelligence",
  "specification-based detection": "intrusion detection",
  "roc curves analysis": "classification metrics",
  "one-class svm": "support vector machine",
  "supervised classification": "supervised learning",
  "neural networks": "machine learning",
  "supervised learning": "machine learning",
  "correlation": "statistical analysis",
  "neural-network-based hybrid ids framework": "hybrid intrusion detection",
  "support vector machines": "support vector machine",
  "ensemble-based techniques": "ensemble learning",
  "analytical hierarchy process (ahp)": "decision-making",
  "intrusion detection techniques": "intrusion detection",
  "decision tree learning": "decision trees",
  "hierarchical ids": "intrusion detection systems",
  "machine learning systems": "machine learning",
  "pattern recognition": "machine learning",
  "distributed systems": "computing systems",
  "execution tracing": "software engineering",
  "neuro-fuzzy networks": "fuzzy logic",
  "unsupervised learning": "machine learning",
  "artificial neural networks": "neural networks",
  "particle swarm optimization": "optimization",
  "insertion attack techniques": "cybersecurity",
  "neural network": "machine learning",
  "deep learning": "neural networks",
  "association rules algorithm": "data mining",
  "multi-criteria decision making (mcdm)": "decision-making",
  "survey": "research methodologies",
  "mobile agent framework": "distributed systems",
  "evasion tactics": "cybersecurity",
  "classification and regression trees": "decision trees",
  "supervised machine learning": "supervised learning",
  "blockchain integration": "blockchain",
  "principal component analysis": "dimensionality reduction",
  "lazy learning": "machine learning",
  "cost-sensitive machine learning": "machine learning",
  "stacknet strategy": "ensemble learning",
  "decision tree": "decision trees",
  "game theory": "mathematical modeling",
  "least square support vector machine": "support vector machine",
  "c4.5 classification": "decision trees",
  "self-organizing maps (som)": "unsupervised learning",
  "synthetic data generation": "data preprocessing",
  "sensor fusion": "data fusion",
  "genetic algorithms": "evolutionary computing",
  "evaluation of passive protocol analysis vulnerabilities": "network protocols",
  "genetic fuzzy systems": "fuzzy logic",
  "maximum likelihood estimation": "statistical analysis",
  "fuzzy inference systems": "fuzzy logic",
  "correlation feature selection": "feature selection",
  "fuzzy inference approach": "fuzzy logic",
  "analytical modeling": "modeling",
  "k-nearest neighbors": "machine learning",
  "misuse detection": "intrusion detection",
  "hybrid algorithm": "optimization",
  "matthews correlation coefficient (mcc)": "classification metrics",
  "long short-term memory (lstm)": "neural networks",
  "protocol detection using signatures": "signature-based detection",
  "denial of service strategies": "cybersecurity",
  "hybrid detection": "intrusion detection",
  "energy-based out-of-distribution detection": "anomaly detection",
  "decision fusion (ensemble) models": "ensemble learning",
  "mutual information feature selection": "feature selection",
  "c4.5 decision tree": "decision trees",
  "data clustering": "clustering",
  "autoencoders": "unsupervised learning",
  "genetic algorithm": "evolutionary computing",
  "feature selection": "data preprocessing",
  "decentralized monitoring": "distributed systems",
  "technique for order of preference by similarity to ideal-solutions (topsis)": "decision-making",
  "challenge-based trust mechanism": "trust management",
  "filter-based feature selection": "feature selection",
  "naive bayesian": "bayesian networks",
  "cart decision tree": "decision trees",
  "anomaly-based intrusion detection": "intrusion detection",
  "convolutional neural network": "neural networks",
  "naive bayes": "bayesian networks",
  "logistic regression": "statistical analysis",
  "chebyshev inequality": "statistics",
  "signature-based misuse detection": "intrusion detection",
  "one-vs-one classification": "classification",
  "explainable artificial intelligence": "explainable ai",
  "principal component analysis (pca)": "dimensionality reduction",
  "modified mutual information-based feature selection (mmifs)": "feature selection",
  "estimation of distribution algorithm": "optimization",
  "word embedding": "natural language processing",
  "reputation-based detection": "anomaly detection",
  "rule-based systems": "expert systems",
  "id3 algorithm": "decision trees",
  "feature scaling": "data preprocessing",
  "openmax": "anomaly detection",
  "cuttlefish optimization algorithm": "optimization",
  "kdd methodology": "data mining",
  "feature selection using bayesian networks and classification and regression trees": "feature selection",
  "deep neural networks": "neural networks",
  "adasyn": "data preprocessing",
  "collaborative ids": "intrusion detection systems",
  "decision analysis": "decision-making",
  "data mining framework": "data mining",
  "machine learning": "computational intelligence",
  "bayesian networks": "probabilistic models",
  "rule induction": "machine learning",
  "collaborative intrusion detection network (cidn)": "intrusion detection systems",
  "ensemble learning": "machine learning",
  "semi-supervised learning": "machine learning",
  "synthetic minority over-sampling technique (smote)": "data preprocessing",
  "peer-to-peer network": "distributed systems",
  "eager learning": "machine learning",
  "libsvm": "support vector machine",
  "explainable ai": "explainable artificial intelligence",
  "anomaly detection": "intrusion detection",
  "static modeling based on event frequency distribution": "modeling",
  "anomaly-based detection": "intrusion detection",
  "optimum allocation scheme": "optimization",
  "bayesian decision model": "bayesian networks",
  "consensus algorithm": "blockchain",
  "ensemble design": "ensemble learning",
  "dynamic modeling based on hmm": "modeling",
  "bayesian networks": "probabilistic models",
  "anomaly detection approach": "intrusion detection",
  "novelty detection": "anomaly detection",
  "restricted boltzmann machine (rbm)": "neural networks",
  "support vector machine": "machine learning",
  "decision trees": "decision trees",
  "krill herd optimization": "optimization",
  "data-dependent decision fusion": "data fusion",
  "bayesian network based inference": "bayesian networks",
  "frequent episodes algorithm": "data mining",
  "layer-wise relevance propagation": "explainable ai",
  "agreement": "collaboration",
  "honeypot system": "network security",
  "random forests algorithm": "ensemble learning",
  "mutual information (mi)": "feature selection",
  "tsk+ fuzzy model": "fuzzy logic",
  "fuzzy logic": "computational intelligence",
  "dynamic application-layer protocol analysis": "network protocols",
  "hybrid intrusion detection": "intrusion detection systems",
  "open set recognition": "classification",
  "acquaintance management": "collaboration",
  "hybrid ids": "intrusion detection systems",
  "random forest": "ensemble learning",
  "clustering": "unsupervised learning",
  "binary classification": "classification",
  "markov blanket model": "bayesian networks",
  "graph-based inference": "graph theory",
  "bayesian learning": "probabilistic models",
  "outlier detection": "anomaly detection",
  "distributed agents": "distributed systems",
  "trust management model": "collaboration",
  "deep belief network (dbn)": "neural networks",
  "distributed ids": "intrusion detection systems",
  "modular ids architecture": "intrusion detection systems",
  "collaborative intrusion detection system": "intrusion detection systems",
  "multilayer perceptron": "neural networks",
  "literature review": "research methodologies",
  "linear genetic programming": "evolutionary computing"
}

category_domains = {
  "robotic systems": "robotics",
  "wireless networks": "networking",
  "computer networks": "networking",
  "network security": "cybersecurity",
  "smart grids": "iot",
  "internet of things": "iot",
  "wireless sensor networks": "iot",
  "security": "cybersecurity",
  "information technology": "computing systems",
  "cybersecurity": "information security",
  "network intrusion detection": "intrusion detection"
}

unique_authors = {
  "lei luo": "lei luo",
  "mohammed a. ambusaidi": "mohammed ambusaidi",
  "ishrat jahan diya": "ishrat jahan diya",
  "huseyin cavusoglu": "hasan cavusoglu",
  "mazin abed mohammed": "mazin abed mohammed",
  "yu-sung wu": "yu-sung wu",
  "yu wang": "yu wang",
  "ravi sankar": "ravi sankar",
  "kasun amarasinghe": "kasun amarasinghe",
  "yanpeng qu": "yanpeng qu",
  "adnan mohsin abdulazeez brifcani": "adnan mohsin abdulazeez",
  "gokhan kul": "gokhan kul",
  "jaroslav zdradek": "jaroslav zdradek",
  "jiannan liu": "jiannan liu",
  "manmohan sharma": "manmohan sharma",
  "muazzam a. khan": "muazzam khan",
  "yoosef b. abushark": "yoosef abushark",
  "srilatha chebrolu": "srilatha chebrolu",
  "fawaz alsolami": "fawaz alsolami",
  "peter scully": "peter scully",
  "oleg kachirski": "oleg kachirski",
  "sehun kim": "sehun kim",
  "jingping song": "jingping song",
  "n. balakrishnan": "balakrishnan n.",
  "jie li": "jie li",
  "wei fan": "wei fan",
  "jeremy frank": "jeremy frank",
  "robert s. sielken": "robert sielken",
  "samira douzi": "samira douzi",
  "yuehui chen": "yuehui chen",
  "adnan helmi azizan": "adnan azizan",
  "lukas kapicak": "lukas kapicak",
  "michael mai": "michael mai",
  "marco pellinacci": "marco pellinacci",
  "md. hasibul alam ratul": "md hasibul alam ratul",
  "adeel abbas": "adeel abbas",
  "zeynep orman": "zeynep orman",
  "lirong chen": "lirong chen",
  "jamal bentahar": "jamal bentahar",
  "mohamed lemine salihi": "mohamed salihi",
  "mohammad zulkernine": "mohammad zulkernine",
  "salvatore j. stolfo": "salvatore stolfo",
  "salma elhag": "salma elhag",
  "arjun remadevi somanathan": "arjun somanathan",
  "christopher price": "christopher price",
  "pavel nevlud": "pavel nevlud",
  "awais aziz shah": "awais shah",
  "nathaniel d. bastian": "nathaniel bastian",
  "annie s. wu": "annie wu",
  "badr hssina": "badr hssina",
  "pietro sabatino": "pietro sabatino",
  "xiangjian he": "xiangjian he",
  "mohsen kahani": "mohsen kahani",
  "gary stein": "gary stein",
  "milos manic": "milos manic",
  "adel nadjaran toosi": "adel toosi",
  "xuan hoai nguyen": "xuan nguyen",
  "salvatore d. morgera": "salvatore morgera",
  "birendra mishra": "birendra mishra",
  "ciza thomas": "ciza thomas",
  "chih-yu hsu": "chih-yu hsu",
  "wei li": "wei li",
  "adriano fagiolini": "adriano fagiolini",
  "md. mahidur rahman": "md mahidur rahman",
  "jie zhang": "jie zhang",
  "yu qiao": "yu qiao",
  "p. sarigiannidis": "sarigiannidis p.",
  "s. sivamohan": "sivamohan s.",
  "alberto fernández": "alberto fernandez",
  "ismail butun": "ismail butun",
  "sayyed majid mazinani": "majid mazinani",
  "srinivasan raghunathan": "srinivasan raghunathan",
  "p. radoglou-grammatikis": "radoglou-grammatikis p.",
  "yuxin ding": "yuxin ding",
  "olga baysal": "olga baysal",
  "kien a. hua": "kien hua",
  "owusu narko-boateng": "owusu boateng",
  "erez zadok": "erez zadok",
  "miroslav bures": "miroslav bures",
  "md. badiuzzaman pranto": "md badiuzzaman pranto",
  "robin gassais": "robin gassais",
  "hesham f. a. hamed": "hesham hamed",
  "gianni valenti": "gianni valenti",
  "francisco herrera": "francisco herrera",
  "vern paxson": "vern paxson",
  "yun li": "yun li",
  "priscila silva": "priscila silva",
  "lance fiondella": "lance fiondella",
  "mohd helmy abd wahab": "mohd wahab",
  "mohamed m. abdeldayem": "mohamed abdeldayem",
  "santosh kumar henge": "santosh henge",
  "jose m. fernandez": "jose fernandez",
  "fatimetou abdou vadhil": "fatimetou vadhil",
  "carol j fung": "carol fung",
  "timothy n. newsham": "timothy newsham",
  "kun xiao": "kun xiao",
  "hany mohamed": "hany mohamed",
  "babak khosravifar": "babak khosravifar",
  "holger dreger": "holger dreger",
  "ali ismail awad": "ali awad",
  "zhiliang zhu": "zhiliang zhu",
  "zunayeed-bin zahir": "zunayeed zahir",
  "xue wang": "xue wang",
  "daniel aloise": "daniel aloise",
  "mohamedade farouk nanne": "mohamed farouk nanne",
  "priyadarsi nanda": "priyadarsi nanda",
  "aida mustapha": "aida mustapha",
  "robin sommer": "robin sommer",
  "truong son pham": "truong pham",
  "alexandre broggi": "alexandre broggi",
  "mohamed faisal elrawy": "mohamed elrawy",
  "bashar ahmad khalaf": "bashar khalaf",
  "anwar haque": "anwar haque",
  "guangping zhuo": "guangping zhuo",
  "jawad ahmad": "jawad ahmad",
  "marcus j. ranum": "marcus ranum",
  "zengjin liu": "zengjin liu",
  "abdulmohsen almalawi": "abdulmohsen almalawi",
  "adebayo felix adekoya": "adebayo adekoya",
  "fatimaezzahra laghrissi": "fatima laghrissi",
  "peter mell": "peter mell",
  "enamul kabir": "enamul kabir",
  "fei chao": "fei chao",
  "man ho au": "man au",
  "johnson p thomas": "johnson p. thomas",
  "gaspard baye": "gaspard baye",
  "bingrui foo": "bingrui foo",
  "maria ajaz": "maria ajaz",
  "saleh alshomrani": "saleh alshomrani",
  "bo dong": "bo dong",
  "kazem fathi": "kazem fathi",
  "anja feldmann": "anja feldmann",
  "crina grosan": "crina grosan",
  "s. s. sridhar": "sridhar s.",
  "quang uy nguyen": "quang nguyen",
  "cik feresa mohd foozy": "feresa foozy",
  "asif irshad khan": "asif khan",
  "gianluigi folino": "gianluigi folino",
  "jiankun hu": "jiankun hu",
  "vaishnavi sivagaminathan": "vaishnavi sivagaminathan",
  "naser ezzati-jivan": "naser ezzati",
  "alka agrawal": "alka agrawal",
  "hesham hefny": "hesham hefny",
  "adel sabry eesaa": "adel eesaa",
  "raees ahmad khan": "raees khan",
  "zhiyuan tan": "zhiyuan tan",
  "bing chen": "bing chen",
  "michel r. dagenais": "michel dagenais",
  "isaac kofi nti": "isaac nti",
  "seungmin lee": "seungmin lee",
  "longzhi yang": "longzhi yang",
  "raouf boutaba": "raouf boutaba",
  "khadija douzi": "khadija douzi",
  "ajith abraham": "ajith abraham",
  "jiong zhang": "jiong zhang",
  "hubert p. h. shum": "hubert shum",
  "yue li": "yue li",
  "gianluca dini": "gianluca dini",
  "john mchugh": "john mchugh",
  "hua wang": "hua wang",
  "jin li": "jin li",
  "ratan guha": "ratan guha",
  "abdullah bawakid": "abdullah bawakid",
  "ang li": "ang li",
  "md mottahir alam": "md alam",
  "thomas h. ptacek": "thomas ptacek",
  "wusheng xu": "wusheng xu",
  "issam aib": "issam aib",
  "shuai wang": "shuai wang",
  "salama a. mostafa": "salama mostafa",
  "wenjuan li": "wenjuan li",
  "anita k. jones": "anita jones",
  "gisung kim": "gisung kim",
  "yongguo mei": "yongguo mei",
  "matthew miller": "matthew miller",
  "viktoras bulavas": "viktoras bulavas",
  "shahid latif": "shahid latif",
  "saurabh bagchi": "saurabh bagchi",
  "antonio bicchi": "antonio bicchi",
  "rajeev kumar": "rajeev kumar",
  "assem alsawy": "assem alsawy",
  "edmond s. l. ho": "edmond ho",
  "wenke lee": "wenke lee",
  "dit-yan yeung": "dit-yan yeung",
  "rebecca bace": "rebecca bace"
}

performance_metrics = {
  "operational cost": "cost metrics",
  "accuracy (acc)": "accuracy",
  "false positive rate": "error metrics",
  "kappa": "classification metrics",
  "classification rate": "accuracy",
  "false alarm rate": "error metrics",
  "detection accuracy": "accuracy",
  "cost per example": "cost metrics",
  "false positives": "error metrics",
  "training time": "efficiency metrics",
  "missed alarms": "error metrics",
  "overall error rate": "error metrics",
  "sensitivity (recall)": "recall",
  "classification accuracy": "accuracy",
  "roc curve": "classification metrics",
  "area under the curve (auc)": "classification metrics",
  "false positives": "error metrics",
  "classification error rate": "error metrics",
  "energy consumption": "efficiency metrics",
  "accuracy rate": "accuracy",
  "misclassification rate": "error metrics",
  "false alarms": "error metrics",
  "intrusion detection rate": "detection metrics",
  "attack detection rates": "detection metrics",
  "detection rate": "detection metrics",
  "error rate": "error metrics",
  "calibration curve": "classification metrics",
  "matthew's correlation coefficient": "classification metrics",
  "f-value": "classification metrics",
  "mean f-measure": "classification metrics",
  "trust value": "trust metrics",
  "average accuracy": "accuracy",
  "f1 score": "classification metrics",
  "f-score": "classification metrics",
  "accuracy": "accuracy",
  "interaction effects": "performance metrics",
  "detection accuracy": "accuracy",
  "true positive rate": "detection metrics",
  "performance overhead": "efficiency metrics",
  "scalability": "efficiency metrics",
  "testing time": "efficiency metrics",
  "false alarm rate": "error metrics",
  "false negative rate": "error metrics",
  "true positive rate": "detection metrics",
  "trustworthiness reduction rate": "trust metrics",
  "transactions per second": "efficiency metrics",
  "false negatives": "error metrics",
  "precision": "classification metrics",
  "correct classification percentage": "accuracy",
  "false positive rate (fpr)": "error metrics",
  "mathew’s correlation coefficient (mcc)": "classification metrics",
  "false alarm rate (far)": "error metrics",
  "total accuracy": "accuracy",
  "processing overhead": "efficiency metrics",
  "consequential cost": "cost metrics",
  "attack detection rate": "detection metrics",
  "area under curve (auc)": "classification metrics",
  "false detection rate (fdr)": "error metrics",
  "processing time": "efficiency metrics",
  "false positive ratio": "error metrics",
  "specificity": "classification metrics",
  "detection rate (dr)": "detection metrics",
  "true detection rate (tdr)": "detection metrics",
  "training time": "efficiency metrics",
  "mean square error (mse)": "regression metrics",
  "true positive rate (tpr)": "detection metrics",
  "false positive rate": "error metrics",
  "cpu utilization": "efficiency metrics",
  "false negative rate": "error metrics",
  "testing time": "efficiency metrics",
  "f-measure": "classification metrics",
  "root mean square error (rmse)": "regression metrics",
  "detection rate": "detection metrics",
  "f-measure": "classification metrics",
  "recall": "classification metrics",
  "roc curve": "classification metrics"
}

ml_models_used = {
  "catboost": "catboost",
  "anfis": "anfis",
  "lstm": "lstm",
  "k-nearest neighbor (knn)": "k-nearest neighbor",
  "convolutional neural networks": "convolutional neural networks",
  "k-nearest neighbour": "k-nearest neighbor",
  "ensemble model": "ensemble models",
  "radial basis function network": "radial basis function network",
  "bayesian networks": "bayesian networks",
  "one-class svm": "support vector machine",
  "gaussian naive bayes": "naive bayes",
  "multivariate normal statistical models": "statistical models",
  "decision tree (dt)": "decision tree",
  "support vector machine": "support vector machine",
  "lstm-mi": "lstm",
  "multilayer perceptron": "multilayer perceptron",
  "decision trees": "decision tree",
  "fuzzy inference systems": "fuzzy inference systems",
  "convolutional neural network": "convolutional neural networks",
  "neural networks": "neural networks",
  "adaboost": "adaboost",
  "k-nn": "k-nearest neighbor",
  "logistic regression": "logistic regression",
  "autoencoder": "autoencoder",
  "decision jungle": "ensemble models",
  "support vector machines": "support vector machine",
  "ripper": "ripper",
  "multivariate adaptive regression splines": "regression splines",
  "extreme gradient boosting (xgboost)": "xgboost",
  "fuzzy c-means clustering": "fuzzy clustering",
  "bilstm": "lstm",
  "support vector machine (svm)": "support vector machine",
  "extra trees classifier (et)": "extra trees classifier",
  "k-nearest neighbor": "k-nearest neighbor",
  "lstm-pca": "lstm",
  "genetic fuzzy system": "genetic fuzzy system",
  "multilayer perceptron (mlp)": "multilayer perceptron",
  "one-class svm": "support vector machine",
  "decision tree (id3)": "decision tree",
  "random forest": "random forest",
  "artificial neural networks": "neural networks",
  "c4.5 decision tree": "decision tree",
  "k-means clustering": "k-means clustering",
  "neural network": "neural networks",
  "svm-rbms": "support vector machine",
  "c4.5": "decision tree",
  "random forest (rf)": "random forest",
  "knn": "k-nearest neighbor",
  "fully-connected neural network": "neural networks",
  "multi-layer perceptron": "multilayer perceptron",
  "naive bayes classifier": "naive bayes",
  "hidden markov model (hmm)": "hidden markov model",
  "classification and regression trees": "decision tree",
  "random forests": "random forest",
  "classification and regression trees (cart)": "decision tree",
  "restricted boltzmann machines": "restricted boltzmann machines",
  "decision tree": "decision tree",
  "naive bayesian": "naive bayes",
  "recurrent neural networks": "recurrent neural networks",
  "ls-svm": "support vector machine",
  "svm": "support vector machine",
  "light gradient boosting machine (lightgbm)": "lightgbm",
  "cart decision tree": "decision tree",
  "decision tree (c4.5)": "decision tree",
  "libsvm": "support vector machine",
  "least square support vector machine": "support vector machine",
  "gradient boosted trees": "gradient boosted trees",
  "self-organizing maps (som)": "self-organizing maps",
  "naive bayes": "naive bayes",
  "stochastic gradient descent classifier": "stochastic gradient descent"
}

dataset = {
  "darpa": "darpa",
  "network tcpdump data": "tcpdump",
  "kdd99": "kdd99",
  "cic-ids2017": "cicids2017",
  "mwn traffic data": "mwn",
  "kdd cup 1999 intrusion detection dataset": "kdd99",
  "nsm dataset": "nsm",
  "darpa 1998 intrusion detection evaluation program": "darpa1998",
  "lbnl traffic data": "lbnl",
  "shell command dataset": "shellcmd",
  "1998 darpa intrusion detection evaluation dataset": "darpa1998",
  "adfa-ld": "adfa-ld",
  "kdd cup 99": "kdd99",
  "ucb traffic data": "ucb",
  "tuids": "tuids",
  "cicids 2017": "cicids2017",
  "kddcup 99": "kdd99",
  "darpa intrusion detection evaluation dataset": "darpa",
  "cic-ids-2017": "cicids2017",
  "honeypot": "honeypot",
  "kddcup'99": "kdd99",
  "real network traffic": "realtraffic",
  "system call dataset": "syscall",
  "kddcup99": "kdd99",
  "kdd 99": "kdd99",
  "mit lincoln laboratory (darpa dataset)": "darpa",
  "pcap files converted to csv": "pcap_csv",
  "unsw-nb15": "unsw-nb15",
  "uci kdd": "kdd99",
  "unsw": "unsw-nb15",
  "darpa intrusion detection evaluation": "darpa",
  "kdd cup 1999": "kdd99",
  "nsl-kdd": "nsl-kdd",
  "cicids2017": "cicids2017",
  "nsdl": "nsdl",
  "sendmail system call data": "sendmail",
  "kdd'99": "kdd99",
  "created datasets": "created",
  "kyoto 2006+": "kyoto2006+"
}

detection_method = {
  "network ids": "network ids",
  "application-based ids": "application-based ids",
  "host-based ids": "host-based ids",
  "hybrid ids": "hybrid ids",
  "network ids (nids)": "network ids (nids)",
  "software ids": "software ids",
  "distributed ids": "distributed ids",
  "collaborative ids": "collaborative ids",
  "network-based ids": "network-based ids",
  "dnn-ids": "dnn-ids",
  "host-based ids (hids)": "host-based ids (hids)",
  "hardware ids": "hardware ids",
  "collaborative ids/nids": "collaborative ids/nids",
  "anomaly-based ids": "anomaly-based ids"
}

attack_types = {
  "penetration attacks": "penetration attacks",
  "buffer overflow": "buffer overflow",
  "u2r": "user to root (u2r)",
  "user to root": "user to root (u2r)",
  "botnet": "botnet",
  "port sweep": "port sweep",
  "scanning attacks": "scanning attacks",
  "web attack": "web attack",
  "probing": "probing",
  "blackhole": "blackhole",
  "port scanning": "port scanning",
  "remote to user (r2l)": "remote to user (r2l)",
  "known attacks": "known attacks",
  "ping sweep": "ping sweep",
  "generic": "generic attack",
  "non-standard port usage": "non-standard port usage",
  "http-based attacks": "http-based attacks",
  "root": "root",
  "spyware": "spyware",
  "intrusions by internal and external users": "intrusions by internal and external users",
  "unknown attacks": "unknown attacks",
  "smurf": "smurf",
  "neptune": "neptune",
  "denial-of-service (dos)": "denial of service (dos)",
  "remote to local": "remote to user (r2l)",
  "analysis": "analysis",
  "wormhole": "wormhole",
  "pod": "pod",
  "spamware": "spamware",
  "packet dropping": "packet dropping",
  "viruses": "viruses",
  "land": "land",
  "glastopt": "glastopt",
  "denial of service attack (dos)": "denial of service (dos)",
  "cross site scripting": "cross-site scripting",
  "probing/surveillance": "probing",
  "exploits": "exploits",
  "malicious logins": "malicious logins",
  "mirai botnet": "mirai botnet",
  "ipsweep": "ip sweep",
  "reconnaissance": "reconnaissance",
  "satan": "satan",
  "random poisoning attacks": "random poisoning attacks",
  "rpl topology attacks": "rpl topology attacks",
  "canarytokens": "canarytokens",
  "fuzzers": "fuzzers",
  "web-based exploits": "web-based exploits",
  "brute force ftp": "brute force ftp",
  "brute force": "brute force",
  "secure shell brute-force attacks": "secure shell brute-force attacks",
  "u2r/data": "user to root (u2r)",
  "script-based attacks": "script-based attacks",
  "backdoor": "backdoor",
  "sinkhole": "sinkhole",
  "infiltration": "infiltration",
  "teardrop": "teardrop",
  "evasion": "evasion",
  "worm": "worm",
  "trojan intrusion": "trojan intrusion",
  "back": "back",
  "flooding": "flooding",
  "shellcode": "shellcode",
  "network scans": "network scans",
  "worms": "worms",
  "force ssh": "force ssh",
  "ransomware": "ransomware",
  "man in the middle": "man-in-the-middle",
  "dionaea": "dionaea",
  "insertion": "insertion attacks",
  "insider attacks": "insider attacks",
  "network attacks": "network attacks",
  "ddos": "distributed denial of service (ddos)",
  "phishing": "phishing",
  "sql injection": "sql injection",
  "spoofing": "spoofing"
}

evaluation_environments = {
  "simulated military network environment": "simulated military network",
  "operational networks at ucb, mwn, and lbnl": "operational networks",
  "simulated traffic": "simulated traffic",
  "simulated environment with multi-robot systems": "simulated multi-robot systems",
  "simulated network using weka": "simulated network (weka)",
  "iot-based smart environments": "iot smart environments",
  "kdd cup 99, nsl-kdd, kyoto 2006+ datasets": "kdd99-nslkdd-kyoto2006+",
  "simulated collaborative hids network": "simulated collaborative hids",
  "simulated network with dataset from uci kdd": "simulated network (uci kdd)",
  "simulated network using cic-ids2017 dataset": "simulated network (cicids2017)",
  "simulated web-based electronic store front application": "simulated web application",
  "simulated network and physical network": "simulated and physical networks",
  "simulated network and real-world deployment": "simulated and real-world deployment",
  "simulated using nsl-kdd dataset": "simulated network (nsl-kdd)",
  "simulated network from unsw-nb15 dataset": "simulated network (unsw-nb15)",
  "test network with ids and target hosts": "test network with ids",
  "simulated lan with kddcup'99 dataset": "simulated lan (kddcup99)",
  "experimental evaluation using cic-ids-2017 dataset": "experimental evaluation (cicids2017)",
  "simulated network using kdd-99 dataset": "simulated network (kdd99)",
  "realistic home automation system": "home automation system",
  "simulated and real network environments": "simulated and real environments",
  "mit lincoln labs environment": "mit lincoln labs",
  "simulated military environment": "simulated military environment",
  "simulated network": "simulated network",
  "simulated environment": "simulated environment",
  "ip multimedia subsystem (ims)": "ims environment",
  "ad hoc wireless network environment": "ad hoc wireless network",
  "simulated using darpa dataset": "simulated network (darpa)",
  "general network environments": "general network environments",
  "not specified": "not specified",
  "kdd 99 dataset": "kdd99",
  "kdd'99 dataset": "kdd99",
  "experimental datasets": "experimental datasets",
  "theoretical analysis based on interaction scenarios": "theoretical analysis",
  "matlab 2016 software environment": "matlab 2016"
}