# Configuration settings for the paper search tool
search:
  default_term: "three way decision in intrusion detection systems"
  max_results: 60  # Maximum number of papers to fetch
  delay: 5
  output: "./data/search_results.csv"
  filter:
    keywords:  # Keywords to filter by
      title: ["three", "3", "3wd", "twd"]
      abstract: ["three", "3", "3wd", "twd"]
download:
  pdf_folder: "./data/papers"
llm:
  output_folder: "./data/llm_responses"
  merged_responses_file: "./data/llm_responses.json"
  delay: 5